baseURL = "https://whysinati.github.io/hugo-rg/"
languageCode = "en"
title = "Rachel S. Gross"
theme = "hugo-initio"

[params]

    name = "Rachel S. Gross"
    description = "Assistant Professor of History • Co-Director of Public History Program • University of Colorado Denver"
    email = "Rachel.Gross@ucdenver.edu"
    twitterhandle = "@rachelsgross"
    year = 2022
    avatar = "images/headshot.jpg"
    avatarclass = "circle"
    background = ""
    banner = "images/mountain.jpg"
    favicon = "images/favicon.ico"
    DateForm = "January 2, 2006"
    date_format = "2. January 2006"

    showSubheader = true
    showResearch = true
    showCurriculumVitae = false
    showProjects = true
    showMedia = true
    showPartners = true

    showRecentWorks = true
    showDownloads = true
    showClients = true

    showFooterContact = true
    showFooterFollowMe = true
    showFooterTextWidget = true
    showFooterFormWidget = false

[[menu.main]]
    name = "research"
    url = "/"
    weight = 1

[params.disqus]

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/nickname"
    icon = "fab fa-facebook-square"
    footer = false
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/rachelsgross"
    icon = "fab fa-twitter-square"
    footer = true
    sharethis = true
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/nickname"
    icon = "fab fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/+nickname"
    icon = "fab fa-google-plus-square"
    footer = false
    sharethis = true
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fab fa-linkedin"
    footer = false
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fab fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/nickname"
    icon = "fab fa-github"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:Rachel.Gross@ucdenver.edu"
    icon = "fas fa-envelope-square"
    footer = true
    sharethis = true
    network = "email"